config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "fridges#index"
  resources :fridges, only: [:show, :create, :update, :destroy] do
    resources :recipes, only: [:index, :show, :create, :destroy]
    resources :ingredients, only: [:new,:create,:update,:edit]
    resources :invite_notifications, only: [:new,:create,:show]
  end
  resources :invite_notifications, only: [:index,:update,:destroy]
  resources :expiry_notifications, only: [:index,:update,:destroy]
  resources :ingredients, only: [:destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    require "json"
    require "open-uri"
    @fridge = Fridge.find(params[:fridge_id])
    @ingredients = @fridge.ingredients
    # url = "https://api.spoonacular.com/recipes/findByIngredients?ingredients=apples,+flour,+sugar&number=2&apiKey=babc8ab6d2624b198c4adbd7021e0043"
    @recipes = ingredients_api_call(@ingredients)
  end

  def show
    raise
  end

  private

  def ingredients_api_call(ingredients)
    base_url = "https://api.spoonacular.com/recipes/findByIngredients?"
    api_key = "&apiKey=#{ENV['API_KEY']}"
    temp_string = "ingredients="

    ingredients.each_with_index do |ingredient, index|
      if index == 0
        temp_string << ingredient.name
      else
        temp_string << ",+#{ingredient.name}"
      end
    end

    url = base_url + temp_string + api_key
    recipes_serialized = URI.open(url).read
    recipes = JSON.parse(recipes_serialized)
  end
end

app/views/recipes/index.html.erb
<%# <% @recipes.each do |recipe| %>
  <%# <p><%= recipe %>
<%# <% end %>
<%# <%= simple_form_for fridge_recipes_path(@fridge), method: :get, class: "d-flex " do %>
  <%# <div class="d-flex">
  <div>
    <%= text_field :query,
      params[:query],
      class: "form-control searchbar",
      placeholder: "Find recipes"
    %>
  <%# </div>
    <%= submit_tag "search" %>
  <%# </div>
<% end %>
<%# <p><%=# @recipes[0] %>

<div class="body-recipes">
  <div class="d-flex justify-content-evenly align-items-start recipe-header-container">
    <div class="button-round">
      <%= link_to "<",fridge_path(Fridge.find(params[:fridge_id])), class: 'button-add' %>
    </div>
    <h2 class="text-center py-4 w-75 pe-5">Recipes</h2>
  </div>
  <div class="p-3">
    <%= form_tag fridge_path(@fridge), method: :get, class: "d-flex", id:"searchbar" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control searchbar-input-show me-1",
        placeholder: "Find a recipe"
      %>
      <%#= submit_tag "Search", class: "searchbar" %>
      <button class="searchbar px-3">
        <i class="fa-solid fa-magnifying-glass"></i>
      </button>
    <% end %>

    <div class="d-flex flex-column align-items-center" data-controller="recipe-modals">
      <% @recipes.each do |recipe| %>
        <!-- Button trigger modal -->
        <div class="card-product mt-3" data-bs-toggle="modal" data-bs-target="<%= "#exampleModal#{recipe["id"]}" %>" data-recipe-id="<%= recipe["id"] %>" data-action="click->recipe-modals#hello" >
          <div class="card-product-infos">
            <h2><%= recipe["title"] %></h2>
            <p>Uses <%= pluralize(recipe["usedIngredientCount"], 'ingredient') %> from the fridge </p>
          </div>
          <p class="card-product-heart">❤️</p>
          <p class="card-product-likes"><%= recipe["likes"] %></p>
          <%= image_tag recipe["image"],
          class:"pe-4 recipe-img" %>
          <%# <div class="bookmark">
            <%#= image_tag("bookmark.png")%>
          <%# </div> %>

        </div>

        <!-- Modal -->
        <div class="modal fade" id="<%= "exampleModal#{recipe["id"]}" %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog ">
            <div class="modal-content  recipe-instruction-card">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><%= recipe["title"] %></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body p-0 recipe-details">
                <%= image_tag recipe["image"] %>
                <div class="ingredients-used">
                  <h4 class="mb-2">Ingredients used from the fridge</h4>
                  <% recipe["usedIngredients"].each_with_index do |ingredient, index| %>
                    <p> <%= "#{index + 1}. #{ingredient["name"]}" %></p>
                  <% end %>
                </div>
                <div class="accordion" id="accordionPanelsStayOpenExample">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                        Missing Ingredients
                      </button>
                    </h2>
                    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingOne">
                      <div class="accordion-body">
                        <% if recipe["missedIngredients"].empty? %>
                          <p>No missing ingredients 😃 Let's start cooking...</p>
                        <% else %>
                          <% recipe["missedIngredients"].each_with_index do |ingredient, index| %>
                            <p> <%= "#{index + 1}. #{ingredient["name"]}" %></p>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                        Instructions
                      </button>
                    </h2>
                    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                      <div class="accordion-body">
                        <div data-recipe-modals-target="modalbody">
                        </div>
                      </div>
                    </div>
                  </div>
                  <%# <div class="accordion-item">
                    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                        Accordion Item #3
                      </button>
                    </h2>
                    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
                      <div class="accordion-body">
                        <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                      </div>
                    </div>
                  </div> %>
                </div>
              </div>
              <div class="modal-footer">
                <%# <button type="button" class="btn button-primary">Lets cook</button> %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div>
  </div>

  </div>
  <div class="buffer">
  </div>
</div>