config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "fridges#index"
  resources :fridges, only: [:show, :create, :update, :destroy] do
    resources :recipes, only: [:index, :show, :create, :destroy]
    resources :ingredients, only: [:new,:create,:update,:edit]
    resources :invite_notifications, only: [:new,:create,:show]
  end
  resources :invite_notifications, only: [:index,:update,:destroy]
  resources :expiry_notifications, only: [:index,:update,:destroy]
  resources :ingredients, only: [:destroy]
end

app/models/fridge.rb
class Fridge < ApplicationRecord
  has_many :fridge_users, dependent: :destroy
  has_many :invite_notifications, dependent: :destroy
  has_many :users, through: :fridge_users
  has_many :ingredients, dependent: :destroy
  has_many :expiry_notifications, dependent: :destroy

  validates :name, presence: true
  # validates :users, presence: true
end

app/controllers/fridges_controller.rb
require 'date'
class FridgesController < ApplicationController
  before_action :set_invite_notifications, only: [:index, :show]
  before_action :set_ingredients_to_expire, only: [:show]
  before_action :set_expiry_notifications, only: [:show]
  before_action :set_fridges_expiring_products, only: [:index]

  def index
    @fridges = current_user.fridges
    @fridge = Fridge.new()
  end

  def show
    if !current_user.fridges.empty?
      @fridge = Fridge.find(params[:id])
    else
      @fridge = Fridge.new
    end

    if params[:query].present?
      @ingredients = @fridge.ingredients.search_by_name(params[:query])
    else
      @ingredients = @fridge.ingredients
    end

    if params[:sort] == "Category"
      @ingredients = @ingredients.sort_by(&:category)
    else
      @ingredients = @ingredients.sort_by(&:exp_date)
    end
  end

  def create
    @fridge = Fridge.new(fridge_params)
    if @fridge.save!
      @fridge_user = FridgeUser.new(user: current_user, fridge: @fridge)
      @fridge_user.save
      redirect_to root_path, notice: 'Fridge was successfully created.'
    else
      render :index, status: :unprocessable_entity
    end
  end

  def update
    @fridge = Fridge.find(params[:id])
    @fridge.update(fridge_params)
    redirect_to fridge_path(@fridge)
  end

  def destroy
    @fridge = Fridge.find(params[:id])
    @fridge.destroy
    redirect_to fridges_path, status: :see_other
  end

  private

  def fridge_params
    params.require(:fridge).permit(:name)
  end

  def set_invite_notifications
    @invite_notifications = InviteNotification.where(receiver_user_id: current_user.id, status: false)
  end

  def set_ingredients_to_expire
    @fridge = Fridge.find(params[:id])
    @ingredients_to_expire = Ingredient.where(fridge: @fridge.id).select do |ingredient|
      ingredient.how_long >= 0 && ingredient.how_long <= 2
    end
  end

  def set_expiry_notifications
    @fridge = Fridge.find(params[:id])
    @expiry_notifications = ExpiryNotification.where(fridge_id: @fridge).select do |notification|
      notification.how_long >= 0 && notification.how_long <= 2
    end
  end

  def set_fridges_expiring_products
    @your_fridges = FridgeUser.where(user: current_user.id)
    @fridges_notifications = @your_fridges.all.select do |fridge|
      fridge_ingredients = Ingredient.where(fridge: fridge.fridge.id)
      ingredients_expiring = fridge_ingredients.all.select do |ingredient|
        ingredient.how_long >= 0 && ingredient.how_long <= 2
      end
      ingredients_expiring.length.positive?
    end
  end
end

app/views/fridges/index.html.erb
<div class="homepage">
  <h1>Let's Save The<br>
    food!</h1>
  <div class="dropdown my-5">
    <button class="btn button-primary btn-add-fridge dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      Add a new fridge
    </button>
    <ul class="dropdown-menu dropdown-card" aria-labelledby="dropdownMenuButton1">
      <li>
        <div class="flex-centered">
          <div>
            <%= simple_form_for [@fridge = Fridge.new] do |f| %>
              <div class="m-3">
                <%= f.input :name, input_html: { class: 'input-home' }, placeholder: "name your fridge" %>
                <%# <%= f.button :submit %>
              </div>
            <% end %>
          </div>
        </div>
      </li>
    </ul>
  </div>

  <% if @fridges.empty? %>
    <h1>You dont have any fridge yet</h1>
  <% else %>

    <div class="fridges-container p-3">
      <h3>Your <%= 'fridge'.pluralize(@fridges.count) %> </h3>
      <% @fridges.each do |fridge| %>
        <div class="fridge-name">
          <%= image_tag("fridge.png", class:"fridge-icon") %>
          <%= link_to fridge.name, fridge_path(fridge) %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="double-buttons">
    <% if @invite_notifications.length > 0 %>
      <p><%= link_to 'Someone invited you to be fridge buddies', invite_notifications_path(@invite_notifications[0].fridge.id) %></p>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, id: "button-logout" %>
    <% end %>
  </div>
</div>

app/views/fridges/show.html.erb
<div class="body-fridge container py-3">
  <div class="mb-4">
    <div class="d-flex justify-content-between align-items-center">
      <div class="dropdown">
        <button class="button-users" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          <h1 class="dropdown-toggle"><%= @fridge.name %></h1>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <% @fridge.users.each do |user|%>
              <div class="users-fridge">
                <%= image_tag("avatarstay.png", class:"avatar-icon") %>
                <li><a class="dropdown-item" href="#"><%= user.username %></a></li>
              </div>
            <% end %>
        </ul>
      </div>
      <h2><%= link_to "Invite People",  new_fridge_invite_notification_path(@fridge), class: "add-people-button" %></h2>
    </div>
    <div id="add-ingredient"class="d-flex justify-content-end">
      <div class="button-round">
        <%= link_to "+", new_fridge_ingredient_path(@fridge), class: "button-add" %>
      </div>
    </div>
    <%= form_tag fridge_path(@fridge), method: :get, class: "d-flex align-items-start mt-5 mb-2", id:"searchbar" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control searchbar-input-show",
        placeholder: "Ingredient..."
      %>
      <%= select_tag "sort", options_for_select(["Expiry date", "Category"], params[:sort]), class: "button-secondary" %>
      <%#= submit_tag "Search", class: "searchbar" %>
      <button class="searchbar px-3">
        <i class="fa-solid fa-magnifying-glass"></i>
      </button>
    <% end %>
  </div>
  <%# if @expiry_notifications.length > 0 %>
      <p><%#='Ingredients are expiring'%></p>
  <%# end %>
  <div class="container-ingredients overflow-auto">
    <% @ingredients.each do |ingredient| %>
    <div class="ingredient-card my-2" data-controller="collapse" data-action="click->collapse#showmore">
      <div class="left-card p-3" data-collapse-target="description">
        <div class="d-flex justify-content-between align-items-center">

          <div class="d-flex justify-content-start align-items-center">
            <% case ingredient.category %>
            <% when 'Fruits & Veggies' %>
              <i class="fa-solid fa-leaf fa-xl p-2"></i>
            <% when 'Eggs & Dairy' %>
              <i class="fa-solid fa-egg fa-xl p-2"></i>
            <% when 'Meat & Poultry' %>
              <i class="fa-solid fa-drumstick-bite fa-xl p-2"></i>
            <% when 'Seafood' %>
              <i class="fa-solid fa-fish fa-xl p-2"></i>
            <% else %>
              <i class="fa-solid fa-bowl-food fa-xl p-2"></i>
            <% end %>
            <h3 class="ingredients-font"> <%= ingredient.name %></h3>
            <p class="ps-2">(<%= ingredient.quantity %> <%= ingredient.unit %>)</p>
           </div>
          <% if ingredient.how_long >= 0 && ingredient.how_long <= 2 %>
            <p class="expiry-warning fw-bold"><%='Expiring soon'%></p>
          <% elsif ingredient.how_long < 0 %>
            <p class="expiry-color fw-bold"><%='Expired'%></p>
          <% end %>
        </div>
          <p class="expiry-font ingredient-card-details"><%= "expires in #{(ingredient.exp_date - Date.today).to_i} days" %></p>
        <div class="d-none" data-collapse-target="ingredients">
          <p class="ingredients-font"><%= ingredient.category %></p>
          <p class="comment"><%= ingredient.comment %>
          <div class="d-flex justify-content-end">
            <%= link_to edit_fridge_ingredient_path(@fridge,ingredient), class:"button-action" do %>
              <i class="fa-solid fa-pen"></i>
            <% end %>

            <%= link_to ingredient_path(ingredient), class:"button-action", data: { turbo_method: :delete, turbo_confirm: "Are you sure"} do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="buffer">
  </div>
</div>