config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "fridges#index"
  resources :fridges, only: [:show, :create, :update, :destroy] do
    resources :recipes, only: [:index, :show, :create, :destroy]
    resources :ingredients, only: [:new,:create,:update,:edit]
    resources :invite_notifications, only: [:new,:create,:show]
  end
  resources :invite_notifications, only: [:index,:update,:destroy]
  resources :expiry_notifications, only: [:index,:update,:destroy]
  resources :ingredients, only: [:destroy]
end

app/models/invite_notification.rb
class InviteNotification < ApplicationRecord
  belongs_to :sender_user, class_name: 'User'
  belongs_to :receiver_user, class_name: 'User'
  belongs_to :fridge

  validates :sender_user, :receiver_user, :email, presence: true
  validates :receiver_user, uniqueness: { scope: [:sender_user, :fridge], message: "invite already exits" }

  validate :sender_and_receiver

  def sender_and_receiver
    errors.add(:receiver_user, "sender and receiver cant be the same") if sender_user == receiver_user
  end

  def accept
  end
end

app/controllers/invite_notifications_controller.rb
class InviteNotificationsController < ApplicationController
    before_action :set_fridge, only: [:new, :create]
    before_action :set_invitation, only: [:update, :destroy]

    def index
      @invite_notifications = InviteNotification.where(receiver_user_id: current_user.id, status: false)
    end

    def show
      @invitation = InviteNotification.find(params[])
    end



    def edit

    end

    def update
      if params[:name] == "accept"
        @invitation.status = true
        @invitation.save!
        @new_fridge = FridgeUser.new(user_id: current_user.id, fridge_id: @invitation.fridge.id)
        @new_fridge.save!
        redirect_to root_path, status: :see_other, notice: 'You joined a new fridge'
      end
    end

    def new
      @invite_notification = InviteNotification.new
    end

    def create
      @invite_notification = InviteNotification.new(invitation_params)
      @invite_notification.sender_user_id = current_user.id
      @receiver = User.find_by(email: invitation_params[:email])
      @invite_notification.status = false
      @invite_notification.receiver_user_id = @receiver.id
      @invite_notification.fridge_id = @fridge.id
      if @invite_notification.save!
        redirect_to fridge_path(@fridge), notice: 'Invitation sent.'
      else
        render :new, status: :unprocessable_entity, notice: 'Invitation failed'
      end
    end

    def destroy
      if params[:name] == "decline"
        @invitation.destroy
        redirect_to root_path, status: :see_other, notice: 'You declined the invitation'
      end
    end

    private

    def invitation_params
      params.require(:invite_notification).permit(:email)
    end

    def set_fridge
      @fridge = Fridge.find(params[:fridge_id])
    end

    def set_invitation
      @invitation = InviteNotification.find(params[:id])
    end
end

app/views/invite_notifications/_form.html.erb
<div class="form-container">
  <%= simple_form_for([@fridge, @invite_notification]) do |f| %>
    <%= f.input :email, placeholder: 'email', input_html: { class: "input-field" }, label: 'Email', label_html: { class: 'form-content' } %>
    <div class="double-buttons-invite">
      <%= f.button :submit, class:'btn button-primary btn-form-invite', value: "Invite" %>
    </div>
  <% end %>
</div>

app/views/invite_notifications/edit.html.erb
<h1>your invitations</h1>


<% @invite_notification.each do |invite| %>
  <%= simple_form_for [invite] do |f| %>
    <%= invite.receiver_user_id %>
    <%= f.button :submit, class:'btn-main my-2' %>
    <%= link_to "decline",invite_notifications_path(invite) , data: { turbo_method: :delete, turbo_confirm: "Are you sure"} %>
    <%= link_to 'Back to all ingredients', root_path, class: 'btn-main my-2' %>
  <% end %>
<% end %>

app/views/invite_notifications/index.html.erb
<h1>your invitations here </h1>


<% @invite_notifications.each do |invite| %>
    <h2><%= invite.receiver_user_id %></h2>
    <h2><%= invite.fridge.id %></h2>
    <h2><%= link_to "accept", invite_notification_path(invite, name: "accept"), data:{ turbo_method: :put } %></h2>
    <h2><%= link_to "decline", invite_notification_path(invite, name: "decline"), data:{ turbo_method: :delete, turbo_confirm: "Are you sure"} %></h2>
<% end %>

app/views/invite_notifications/new.html.erb
<div class="container py-4 edit-container">
  <div class="d-flex justify-content-between align-items-start ">
    <div class="button-round">
      <%= link_to "<",fridge_path(@fridge), class: 'button-add' %>
    </div>
    <h2 class="text-center py-4 w-75 pe-5">Add a buddy</h2>
  </div>
  <%= render "form", fridge: @fridge, fridge: @invite_notification %>
</div>